//@ts-check

//https://claude.ai/public/artifacts/c9fb4e17-0653-407d-b945-74eedea7996d

//Code generated by Claude.js

/**
 * imp-h.js - Bare bones HTML importer for web components
 * Imports HTML content between <!-- begin --> and <!-- end --> comments
 * into the shadow DOM of elements with imp-h attribute
 * Supports import map resolution for HTML paths
 */

/**
 * Resolves a path using the import map if available
 * @param {string} specifier - The import specifier (e.g., "my-package/root.html")
 * @returns {string} The resolved URL
 */
function resolveWithImportMap(specifier) {
  // Get the import map from the document
  const importMapScripts = Array.from(document.querySelectorAll('script[type="importmap"]'));
  
  if (importMapScripts.length === 0) {
    // No import map, return specifier as-is
    return specifier;
  }
  
  for(const importMapScript of importMapScripts){
    const importMap = JSON.parse(importMapScript.textContent);
    const imports = importMap.imports || {};
    
    // Check for exact match first
    if (imports[specifier]) {
      return imports[specifier];
    }
    
    // Check for prefix matches (e.g., "my-package/" mapping)
    for (const [key, value] of Object.entries(imports)) {
      if (key.endsWith('/') && specifier.startsWith(key)) {
        // Replace the prefix with the mapped value
        return specifier.replace(key, value);
      }
    }
  }

    
  // No match found, return original specifier
  return specifier;
  
}

// Find all elements with imp-h attribute
const elements = document.querySelectorAll('[imp-h]');

elements.forEach(async (element) => {
  if(!(element instanceof HTMLElement)) return;
  const htmlPath = element.getAttribute('imp-h');
  
  if (!htmlPath) {
    console.warn('imp-h attribute is empty', element);
    return;
  }

  try {
    // Resolve the path using import map
    const resolvedPath = resolveWithImportMap(htmlPath);
    
    // Fetch the HTML file
    const response = await fetch(resolvedPath);
    
    if (!response.ok) {
      throw new Error(`Failed to fetch ${resolvedPath}: ${response.status} ${response.statusText}`);
    }
    
    const html = await response.text();
    
    // Extract content between <!-- begin --> and <!-- end -->
    const beginMarker = '<?start>';
    const endMarker = '<?end>';
    
    const beginIndex = html.indexOf(beginMarker);
    const endIndex = html.lastIndexOf(endMarker);
    
    if (beginIndex === -1 || endIndex === -1) {
      throw new Error(`Could not find begin/end markers in ${resolvedPath}`);
    }
    
    // Extract the content between the markers
    const content = html.substring(beginIndex + beginMarker.length, endIndex).trim();
    const templ = document.createElement('template');
    
    templ.innerHTML = content;
    
    
    // Create shadow DOM if it doesn't exist
    if (!element.shadowRoot) {
      element.attachShadow({ mode: 'open' });
    }
    const clone = templ.content.cloneNode(true);
    element.shadowRoot?.appendChild(clone);
    const id = `a-${crypto.randomUUID()}`;
    templ.id = id;
    element.dataset.impH = id; 
    document.head.appendChild(templ);
    
    
  } catch (error) {
    console.error(`Error loading HTML for element:`, element, error);
  }
});